#!/usr/bin/env python3
"""Apply Pane release public keys from pane-release-keys.public.json across the repo."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[3]
PUBLIC_JSON = Path(__file__).resolve().parent / "pane-release-keys.public.json"
EXTENSION_IDS_TS = (
    REPO_ROOT / "packages/browseros-agent/apps/app/lib/constants/paneExtensionIds.ts"
)


def load_public_keys() -> dict:
    if not PUBLIC_JSON.exists():
        raise SystemExit(f"Missing {PUBLIC_JSON}. Run generate-pane-release-keys.py first.")
    return json.loads(PUBLIC_JSON.read_text())


def write_extension_ids_ts(data: dict) -> None:
    agent = data["extensions"]["agent"]["id"]
    claw = data["extensions"]["claw"]["id"]
    EXTENSION_IDS_TS.write_text(
        f"""/**
 * Pane extension IDs — derived from manifest.key in each WXT app.
 * Generated by scripts/release/generate-pane-release-keys.py — do not edit.
 */
export const PANE_AGENT_EXTENSION_ID = '{agent}' as const

export const PANE_CLAW_EXTENSION_ID = '{claw}' as const
"""
    )


def patch_file(path: Path, transform) -> None:
    if not path.exists():
        return
    original = path.read_text()
    updated = transform(original)
    if updated != original:
        path.write_text(updated)
        print(f"  updated {path.relative_to(REPO_ROOT)}")


def apply(data: dict) -> None:
    sparkle_pub = data["sparkle"]["publicKeyBase64"]
    agent = data["extensions"]["agent"]
    claw = data["extensions"]["claw"]

    sparkle_patterns = [
        (
            re.compile(r"(<key>SUPublicEDKey</key>\s*<string>)[^<]+(</string>)"),
            rf"\g<1>{sparkle_pub}\g<2>",
        ),
        (
            re.compile(r'(<key>SUPublicEDKey</key>\s*<string>)[^<]+(</string>)'),
            rf"\g<1>{sparkle_pub}\g<2>",
        ),
        (
            re.compile(r'(constexpr char kEdDSAPublicKey\[\] =\s*")[^"]+(";)'),
            rf'\g<1>{sparkle_pub}\g<2>',
        ),
        (
            re.compile(r'(inline constexpr char kServerUpdatePublicKey\[\] =\s*")[^"]+(";)'),
            rf'\g<1>{sparkle_pub}\g<2>',
        ),
    ]

    for rel in (
        "packages/browseros/chromium_patches/chrome/app/app-Info.plist",
        "packages/browseros/resources/entitlements/Info.plist.additions",
        "packages/browseros/chromium_patches/chrome/browser/win/winsparkle_glue.cc",
        "packages/browseros/chromium_patches/chrome/browser/browseros/server/browseros_server_constants.h",
    ):
        path = REPO_ROOT / rel

        def transform(text: str, patterns=sparkle_patterns) -> str:
            for pattern, repl in patterns:
                text = pattern.sub(repl, text)
            # Chromium patch files prefix added lines with '+' — fall back to literal replace.
            text = text.replace("LzQmcNuTsdB3/dsivo0eeN+jPfDoriRHAkkEJcfFs2A=", sparkle_pub)
            return text

        patch_file(path, transform)

    chromium_patch_root = REPO_ROOT / "packages/browseros/chromium_patches"
    if chromium_patch_root.is_dir():
        for path in chromium_patch_root.rglob("*"):
            if not path.is_file():
                continue

            def transform_chromium(text: str) -> str:
                text = text.replace("LzQmcNuTsdB3/dsivo0eeN+jPfDoriRHAkkEJcfFs2A=", sparkle_pub)
                text = re.sub(r"bflpfmnmnokmjhmgnolecpppdbdophmk", agent["id"], text)
                text = re.sub(r"pjimfkbpehlcllblajnpfamdfjhhlgkc", claw["id"], text)
                return text

            patch_file(path, transform_chromium)

    def patch_wxt_agent(text: str) -> str:
        text = re.sub(
            r"key: '[^']+'",
            f"key: '{agent['manifestKeyBase64']}'",
            text,
            count=1,
        )
        return re.sub(
            r"// Extension ID will be [a-z0-9]+",
            f"// Extension ID will be {agent['id']}",
            text,
        )

    def patch_wxt_claw(text: str) -> str:
        return re.sub(
            r"key: '[^']+'",
            f"key: '{claw['manifestKeyBase64']}'",
            text,
            count=1,
        )

    patch_file(REPO_ROOT / "packages/browseros-agent/apps/app/wxt.config.ts", patch_wxt_agent)
    patch_file(REPO_ROOT / "packages/browseros-agent/apps/claw-app/wxt.config.ts", patch_wxt_claw)

    def patch_constants(text: str) -> str:
        text = re.sub(
            r'inline constexpr char kAgentExtensionId\[\] =\s*"[^"]+";',
            f'inline constexpr char kAgentExtensionId[] =\n    "{agent["id"]}";',
            text,
        )
        text = re.sub(
            r'inline constexpr char kBrowserClawExtensionId\[\] =\s*"[^"]+";',
            f'inline constexpr char kBrowserClawExtensionId[] =\n    "{claw["id"]}";',
            text,
        )
        return text

    patch_file(
        REPO_ROOT / "packages/browseros/chromium_patches/chrome/browser/browseros/core/browseros_constants.h",
        patch_constants,
    )

    def patch_build_gn(text: str) -> str:
        text = re.sub(
            r'"[a-z]{32}\.crx",\s*# Agent',
            f'"{agent["id"]}.crx",  # Agent',
            text,
        )
        return re.sub(
            r'\+\s*"[a-z]{32}\.crx",\s*# Bug Reporter\n',
            "",
            text,
        )

    patch_file(
        REPO_ROOT / "packages/browseros/chromium_patches/chrome/browser/browseros/bundled_extensions/BUILD.gn",
        patch_build_gn,
    )

    def patch_bundled_py(text: str) -> str:
        text = re.sub(
            r'PANE_BUNDLED_EXTENSION_IDS: Dict\[str, str\] = \{[^}]+\}',
            f'PANE_BUNDLED_EXTENSION_IDS: Dict[str, str] = {{\n    "{agent["id"]}": "Pane agent",\n}}',
            text,
            flags=re.DOTALL,
        )
        text = re.sub(
            r'"[a-z]{32}": "Pane agent"',
            f'"{agent["id"]}": "Pane agent"',
            text,
        )
        text = re.sub(
            r'"pjimfkbpehlcllblajnpfamdfjhhlgkc": "Pane Claw app"',
            f'"{claw["id"]}": "Pane Claw app"',
            text,
        )
        return text

    patch_file(
        REPO_ROOT / "packages/browseros/build/modules/extensions/bundled_extensions.py",
        patch_bundled_py,
    )

    for rel in (
        ".github/workflows/release-agent-extension.yml",
        ".github/workflows/release-claw-app.yml",
        "updates/extensions/bundled-manifest.xml",
        "updates/extensions/update-manifest.xml",
        "packages/browseros-agent/apps/server/src/api/utils/cors.ts",
        "packages/browseros-agent/apps/server/tests/api/utils/cors.test.ts",
        "packages/browseros-agent/apps/server/tests/api/routes/index.test.ts",
        "packages/browseros-agent/scripts/dev/inspect-ui.ts",
        "packages/browseros/build/modules/extensions/bundled_extensions_test.py",
        "packages/browseros-agent/scripts/release/generate-extension-update-manifest.ts",
        ".cursor/skills/test-ui/SKILL.md",
        "packages/browseros-agent/.claude/skills/test-ui/SKILL.md",
    ):
        path = REPO_ROOT / rel

        def transform(text: str) -> str:
            text = re.sub(r"bflpfmnmnokmjhmgnolecpppdbdophmk", agent["id"], text)
            text = re.sub(r"pjimfkbpehlcllblajnpfamdfjhhlgkc", claw["id"], text)
            return text

        patch_file(path, transform)

    test_id = REPO_ROOT / "packages/browseros-agent/test-id.cjs"
    test_id.write_text(
        f"""const crypto = require('node:crypto')
const keyPem = '{agent["manifestKeyBase64"]}'

const pubKeyBytes = Buffer.from(keyPem, 'base64')
const hash = crypto.createHash('sha256').update(pubKeyBytes).digest()
const hex = hash.toString('hex').slice(0, 32)

const id = Array.from(hex)
  .map((c) => String.fromCharCode('a'.charCodeAt(0) + parseInt(c, 16)))
  .join('')

console.log('ID:', id)
"""
    )
    print(f"  updated {test_id.relative_to(REPO_ROOT)}")

    write_extension_ids_ts(data)
    print(f"Applied Pane release keys from {PUBLIC_JSON.name}")


def main() -> None:
    apply(load_public_keys())


if __name__ == "__main__":
    main()
