/**
 * Pane extension IDs — derived from manifest.key in each WXT app.
 * Generated by scripts/release/generate-pane-release-keys.py — do not edit.
 */
export const PANE_AGENT_EXTENSION_ID =
  'biedncddmddkpapdplhcnkhhplnfgbif' as const

export const PANE_CLAW_EXTENSION_ID =
  'cmlhocfcmfhegcblpkphkcnoiglonenf' as const
